#!/bin/bash

URLLIST="http://surfkeskus.homelinux.org/index.html http://surfkeskus.homelinux.org/surffiilis.jpg http://surfkeskus.homelinux.org/stylesheet.css"

while [ 1 ] ; do
  count="`ps -A | grep -c wget`"
  if (( "$count"  > 100 )) ; then
	echo "Sleeping..."
	sleep 1
  fi
  for url in $URLLIST ; do
    wget "$url" -o /dev/null -O /dev/null || echo "$count failed" && echo "$count success" &
  done
done
